version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: mssql
    ports:
      - 1433:1433
    env_file:
      -  .env
    volumes:
      - sqlsystem:/var/opt/mssql/ # or /var/opt/sqlserver
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - ${PWD}/mssql-conf.config:/opt/mssql/bin/mssql-conf.config
      
  sqlpad:
    image: sqlpad/sqlpad:latest
    hostname: 'sqlpad'
    ports:
      - 3000:3000
    env_file:
      -  .env
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server Demo
      SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver
      SQLPAD_CONNECTIONS__sqlserverdemo__host: mssql
      SQLPAD_CONNECTIONS__sqlserverdemo__database: master
      SQLPAD_CONNECTIONS__sqlserverdemo__username: sa
      SQLPAD_CONNECTIONS__sqlserverdemo__password: ${MSSQL_SA_PASSWORD:-}
    volumes:
      - sqlpad-volume:/var/lib/sqlpad

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  sqlconfig:
  sqlpad-volume: