version: '3.8'
services:
  mssql:
    image: ${TAG:-latest}
    hostname: mssql
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 1433:1433
    env_file:
      -  .env
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - ${pwd}/mssql-conf.config:/opt/mssql/bin/mssql-conf.config
      

  sqlpad:
    # To use Dockerfile at root of this project, use build instead of image
    # build: ../../
    image: sqlpad/sqlpad:latest
    hostname: 'sqlpad'
    ports:
      - 3000:3000
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server Demo
      SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver
      SQLPAD_CONNECTIONS__sqlserverdemo__host: mssql
      SQLPAD_CONNECTIONS__sqlserverdemo__database: master
      SQLPAD_CONNECTIONS__sqlserverdemo__username: sa
      SQLPAD_CONNECTIONS__sqlserverdemo__password: ${MSSQL_SA_PASSWORD:-}
    volumes:
      - sqlpad-volume:/var/lib/sqlpad

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  sqlconfig:
  sqlpad-volume: